### ISSUE TITLE
Segment ngSwitch binds to model

### ISSUE THREAD

**Issue by yhalwani** [driftyco/ionic-preview-app#104]
There might be an issue with how you are demonstrating how to use the segment component in:
http://ionicframework.com/docs/components/#segment
As I understand it AngularJS creates a new child scope for the ngSwitch which is lost to the parent scope when written to. This creates a problem in the Ionic framework when you try to access an element in the ngSwitch cases using @ViewChild with ElementRef for example. 
According to
https://github.com/angular/angular.js/wiki/Understanding-Scopes#ng-switch
best practices requires there to be a "." in the ngModel so you bind to an object "pet" instead of the primitive as it is now. I may be way off base and misunderstanding the situation, in any case any clarification is appreciated!

**Comment by brandyscarney** [comment]
Thanks for the issue! You are linking to documentation from an old version of AngularJS, version 1.x. The latest versions of Angular do not use `$scope` and don't have the same issues. 

I'm not sure I understand the problem in Ionic. Here is the latest documentation on ngSwitch: https://angular.io/docs/ts/latest/api/common/index/NgSwitch-directive.html

If you can explain the issue that you are specifically running into with ngSwitch and ViewChild I could be of more help. 🙂

**Comment by yhalwani** [comment]
Thanks for the response and sorry for the miss understanding! You're correct the scoping issue isn't in the latest version Angular, my problem isn't an issue with Ionic then. 

Specifically I am attempting to create a google map in one segment with ngSwitch which requires the use of ViewChlid. However, as outlined in your link to the new Angular documentation, ngSwitch only "stamps out" nested views when their match expression value matches the value of the switch expression. So ViewChild can't find the <div> in the segment ngSwitchCase where the map would go and is therefore undefined. Basically ViewChild doesn't seem able to access elements in ngSwitchCases.

I've outlined the problem better on stackoverflow at:
http://stackoverflow.com/questions/43745022/

For anyone who is interested as a work around I am currently using the API at angular-maps.com which doesn't require the use of ViewChild

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
