### ISSUE TITLE
list item not working

### ISSUE THREAD

**Issue by 306825** [driftyco/ionic-preview-app#105]
Hi, I am very new to ionic. My list item is not appearing properly. All I see when I render the app on the browser is something like this:

Gender
Femal Male

What I am expecting to see is a list item labeled gender and when I click on it I should get a popup with the list of options. Below is the html. Any assistance will be greatly appreciated.

<ion-view view-title="Search">
  <ion-content>
  <ion-list>
    <ion-item>
      <ion-label>Gender</ion-label>
      <ion-select [(ngModel)]="gender">
        <ion-option value="f" selected="true">Female</ion-option>
        <ion-option value="m">Male</ion-option>
      </ion-select>
    </ion-item>
  </ion-list>
  </ion-content>
</ion-view>

**Comment by mhartington** [comment]
Hi there! This doesn't appear to be an issue with the framework it self, so I'm going to close it. Please post your question on the [Ionic Forum](https://forum.ionicframework.com) instead.
