### ISSUE TITLE
searchbar demo slow for 1000+ items

### ISSUE THREAD

**Issue by susanlinsfu** [driftyco/ionic-preview-app#12]
I have tested with 1000-2000 items (length on average of 40 characters) . To search for an item is VERY slow . It seems to take about 5 seconds on a low wend android device to see the character show up, then another 10 seconds for the result to filter based on the criteria. 1000 items is not that much, could this be improved?

**Comment by mhartington** [comment]
Hi there! Issues for this repo are related to the preview app and it's functionality, not to issue related to the framework.


Please open an issue here 
https://github.com/driftyco/ionic/issues

Cheers!
