### ISSUE TITLE
scrolling still active by sliding list

### ISSUE THREAD

**Issue by mbakker96** [driftyco/ionic-preview-app#14]
The scrolling is still active when I activate the sliding list for extra options by a list. By native apps it is turned off automatic

**Comment by brandyscarney** [comment]
Hey @mbakker96, I don't understand the issue? Are you talking about sliding an item to the left to reveal the options? Maybe you could provide a codepen/plunker?

**Comment by astec** [comment]
Hi @brandyscarney , I think yes, it's about sliding an item to the left to release options like "Delete" for example. When you slide and option is visible the list is not longer scrollable (up/down) until an option choosen/canceled.

**Comment by brandyscarney** [comment]
@astec So that is actually native. 

We have been using the WWDC app to mock native functionality: https://itunes.apple.com/us/app/wwdc/id640199958?mt=8

You can also take a look at the native app "find my friends" or "reminders" that come with iOS.

**Comment by mbakker96** [comment]
In the native app you can't scroll up and down when you activate 'slide options' and in the ionic app it is possible  to keep scrolling. 

Met vriendelijke groet  / Regards,

Martijn Bakker

Software (web) development 
www.mar-bakker.nl - www.marbakkerdev.nl - www.zapion.nl

**Comment by mhartington** [comment]
Hi there! Issues for this repo are related to the preview app and it's functionality, not to issue related to the framework.


Please open an issue here 
https://github.com/driftyco/ionic/issues

Cheers!
