### ISSUE TITLE
Alert.AddInput() type:'text'

### ISSUE THREAD

**Issue by naveenkonduru** [driftyco/ionic-preview-app#15]
The following code still working as radio when type is 'text'   

 let alert = Alert.create();
    alert.setTitle('Lightsaber color');
    alert.addInput({
      type: 'text'
    });

**Comment by mhartington** [comment]
Hi there! Issues for this repo are related to the preview app and it's functionality, not to issue related to the framework.


Please open an issue here 
https://github.com/driftyco/ionic/issues

Cheers!
