### ISSUE TITLE
Ionic list flexbox does not work

### ISSUE THREAD

**Issue by ikins3924** [driftyco/ionic-preview-app#16]
Inside ionic list item, icon or avatar is aligned vertically using flexbox:

```
.item {
    display: flex;
    align-items: center;
    ...
}
```

However, when the list item is button, "display: flex;" seems not working in Safari, so that its child ion-icon is aligned to the top:

**Same CSS:**
**Chrome:**
![screen shot 2016-04-15 at 11 33 27 pm](https://cloud.githubusercontent.com/assets/18486622/14566547/8f4fe78c-0362-11e6-9ecf-7aa3c7613d31.png)
**Safari:**
![screen shot 2016-04-15 at 11 33 03 pm](https://cloud.githubusercontent.com/assets/18486622/14566538/86bf1476-0362-11e6-85e8-42de289ea325.png)

The problem seems only appear in button container, if I use the ion-item instead of button, the alignment is all correct. Also if I use Chrome instead of Safari, no problem at all.

Has anyone run into the same problem? Any suggestion?

**Comment by mhartington** [comment]
Hi there! Issues for this repo are related to the preview app and it's functionality, not to issue related to the framework.


Please open an issue here 
https://github.com/driftyco/ionic/issues

Cheers!
