### ISSUE TITLE
Typo in toolbar

### ISSUE THREAD

**Issue by viki53** [driftyco/ionic-preview-app#17]
In the toolbar component demo, there's a tiny typo:

It says *Pirmary* instead of *Primary*

https://github.com/driftyco/ionic-preview-app/blob/faa42707395feaf92174b90e1218d25e43b91b91/app/pages/toolbar/colors/pages.ts#L67

Cheers

**Comment by brandyscarney** [comment]
Thanks for the issue. It's fixed now. :smile:
