### ISSUE TITLE
Run command "ionic serve" in a terminal, then error

### ISSUE THREAD

**Issue by stonelee74** [driftyco/ionic-preview-app#18]
Error: Import directives may not be used within control directives or mixins.
        on line 34 of node_modules/ionic-angular/components.core.scss
>>   @import "fonts/ionicons";
   --^

**Comment by stonelee74** [comment]
Running 'serve:before' gulp task before serve
[18:12:08] Starting 'clean'...
[18:12:08] Finished 'clean' after 169 ms
[18:12:08] Starting 'watch'...
[18:12:08] Starting 'sass'...
[18:12:08] Starting 'html'...
[18:12:08] Starting 'fonts'...
[18:12:08] Starting 'scripts'...
node_modules/ionic-angular/components.core.scss
Error: Import directives may not be used within control directives or mixins.
        on line 34 of node_modules/ionic-angular/components.core.scss
>>   @import "fonts/ionicons";
   --^

[18:12:08] Finished 'sass' after 170 ms
[18:12:08] Finished 'scripts' after 161 ms
[18:12:08] Finished 'fonts' after 194 ms
[18:12:08] Finished 'html' after 265 ms
TypeScript error: /Users/liyan/PHP/ionic-preview-app/app/directives/helpers.ts(42,23): Error TS2339: Property 'currentStyle' does not exist on type 'HTMLElement'.
TypeScript error: /Users/liyan/PHP/ionic-preview-app/app/directives/helpers.ts(43,30): Error TS2339: Property 'currentStyle' does not exist on type 'HTMLElement'.
TypeScript error: /Users/liyan/PHP/ionic-preview-app/app/directives/helpers.ts(52,23): Error TS2339: Property 'currentStyle' does not exist on type 'HTMLElement'.
TypeScript error: /Users/liyan/PHP/ionic-preview-app/app/directives/helpers.ts(53,31): Error TS2339: Property 'currentStyle' does not exist on type 'HTMLElement'.
7.1 MB bytes written (23.23 seconds)
[18:12:39] Finished 'watch' after 31 s
[18:12:39] Starting 'serve:before'...
[18:12:39] Finished 'serve:before' after 9.69 μs

**Comment by brandyscarney** [comment]
Hey, there is an issue here for this: https://github.com/driftyco/ionic/issues/6258

Please see my comment for a temporary work around until we fix it in the starters: https://github.com/driftyco/ionic/issues/6258#issuecomment-212728777

**Comment by stonelee74** [comment]
@brandyscarney many thanks
