### ISSUE TITLE
Got error while run the program

### ISSUE THREAD

**Issue by akshay-padalkar26** [driftyco/ionic-preview-app#2]
i am runing the same program but geeting error that it cannot resolve "./../../directive/helper."   how these directive should include ,help me

**Comment by brandyscarney** [comment]
Did you run all of these steps?

```
git clone git@github.com:driftyco/ionic-preview-app.git
cd ionic-preview-app
npm install
ionic serve
```

**Comment by rendymarojahan** [comment]
Just try the basic first
http://ionicframework.com/docs/v2/components/#action-sheets

**Comment by brandyscarney** [comment]
Closing this as it shouldn't be an issue in the latest version. Let me know if you still get the error after following the steps above.
