### ISSUE TITLE
ionic server Error :  app/directives/helpers.ts Error TS2339

### ISSUE THREAD

**Issue by SoaringTiger** [driftyco/ionic-preview-app#21]
`app/directives/helpers.ts(44,23): Error TS2339: Property 'currentStyle' does not exist on type 'HTMLElement'.

app/directives/helpers.ts(45,30): Error TS2339: Property 'currentStyle' does not exist on type 'HTMLElement'.

app/directives/helpers.ts(54,23): Error TS2339: Property 'currentStyle' does not exist on type 'HTMLElement'.

app/directives/helpers.ts(55,31): Error TS2339: Property 'currentStyle' does not exist on type 'HTMLElement'.`

**Comment by SoaringTiger** [comment]
the samples not work on Chrome but work ok on safari.

`Uncaught TypeError: m.values is not a function     app.bundle.js:30387 `

**Comment by fvsaddam** [comment]
i have same problem, but it's still work well.

**Comment by dragonahao** [comment]
I occur within chrome ,what can i do something else?
