### ISSUE TITLE
Make Sass files only affect the current page

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-preview-app#22]
Currently the Sass is not contained to only affect the page it is next to. These should all be wrapped in a page specific class. This will help out in the future so we know exactly where to look to find the code to style the page.

- cards need to be thoroughly looked through
- the tabs should be able to be achieved by using base/contrast. we should show these off.

**Comment by mbakker96** [comment]
Will look to it this week

**Comment by brandyscarney** [comment]
Thanks @mbakker96, but I am going to handle this one now. :smile:

**Comment by mbakker96** [comment]
Hahaha is good

Op wo 27 apr. 2016 om 23:29 schreef Brandy Carney <notifications@github.com>

> Thanks @mbakker96 <https://github.com/mbakker96>, but I am going to
> handle this one now. [image: :smile:]
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-preview-app/issues/22#issuecomment-215235379>
>
-- 
Met vriendelijke groet  / Regards,

Martijn Bakker

Software (web) development
www.mar-bakker.nl - www.marbakkerdev.nl - www.zapion.nl
