### ISSUE TITLE
Can't edit or add content into tab

### ISSUE THREAD

**Issue by muhammedmuhsin** [driftyco/ionic-preview-app#27]
Hi i tried to build an android app using  tabed cutePuppyPics 
i edited all the content inside tabs and build after building all pages loading old contents and also app is showing old contents 

Pleas help me 
Thank you

**Comment by mhartington** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:
