### ISSUE TITLE
Alert input's property 'label' seem not work

### ISSUE THREAD

**Issue by DarrenHou1993** [driftyco/ionic-preview-app#30]
![image](https://cloud.githubusercontent.com/assets/9291785/15601314/3bcb7e2a-2421-11e6-848c-3fc6934059ce.png)
![image](https://cloud.githubusercontent.com/assets/9291785/15601326/481323c2-2421-11e6-94a3-8170d1d0086b.png)
Whether I add or not 'label',There's no change here.

**Comment by mhartington** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself, but rather a question about the framework. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:
