### ISSUE TITLE
Material design theme appears to be missing some style

### ISSUE THREAD

**Issue by marcoskubis** [driftyco/ionic-preview-app#32]
I installed the latest version of ionic 2 and I notice some differences between the android theme in my installed ionic app and the this ionic preview app. I'm forgetting something? Any custom css?

Ionic preview app:
<img src="https://cdn.discourse.org/ionicframework/uploads/default/optimized/3X/5/4/543b6475bece41e8b16fd912d1160760f67068bc_1_318x499.jpg">

My app:
<img src="https://cdn.discourse.org/ionicframework/uploads/default/original/3X/f/4/f4f666c405c7fdee715e5091db64ee7cdd712176.jpg" width="281" height="500">

**Comment by brandyscarney** [comment]
The card demos get a custom background:

```
ion-content.cards-bg {
  background-color: #f4f4f7;
}
```

https://github.com/driftyco/ionic-preview-app/blob/master/app/pages/cards/advanced-social/template.html#L6
https://github.com/driftyco/ionic-preview-app/blob/master/app/pages/cards/advanced-map/styles.scss#L14-L16

**Comment by marcoskubis** [comment]
See the pictures. I'm not talking about the bg color. Se the `h2` and  `p` tags, they have a padding or margin much bigger than the ionic preview app. The buttons seem differents too. I've look at all the custom styles in this preview app and nothing explain this difference.

**Comment by brandyscarney** [comment]
Can you paste your markup? This is the markup for the social card:

```
<ion-card>

  <ion-item>
    <ion-avatar item-left>
      <img src="img/marty-avatar.png">
    </ion-avatar>
    <h2>Marty McFly</h2>
    <p>November 5, 1955</p>
  </ion-item>

  <img src="img/advance-card-bttf.png">

  <ion-card-content>
    <p>Wait a minute. Wait a minute, Doc. Uhhh... Are you telling me that you built a time machine... out of a DeLorean?! Whoa. This is heavy.</p>
  </ion-card-content>

  <ion-row>
    <ion-col>
      <button primary clear small>
        <ion-icon name='thumbs-up'></ion-icon>
        <div>12 Likes</div>
      </button>
    </ion-col>
    <ion-col>
      <button primary clear small>
        <ion-icon name='text'></ion-icon>
        <div>4 Comments</div>
      </button>
    </ion-col>
    <ion-col center text-center>
      <ion-note>
        11h ago
      </ion-note>
    </ion-col>
  </ion-row>

</ion-card>
```

Generating a new page and using this markup with no custom css results in the following:

![screen shot 2016-06-01 at 9 09 27 pm](https://cloud.githubusercontent.com/assets/6577830/15730732/2a41827e-283d-11e6-89cb-83bffc4d976e.png)

**Comment by marcoskubis** [comment]
I do a fresh install, paste your code and it's working now. But before, the a copy and paste the code from the ionicframwork website. I feel like a liar now hehe. Thank you so much.
![ionic](https://cloud.githubusercontent.com/assets/3844716/15731161/5aa17332-2849-11e6-8105-ef945a889b1f.jpg)

**Comment by brandyscarney** [comment]
Actually the code in the docs isn't the same as in the preview app. I just found an issue for it (that I forgot about), so we'll have to fix that. :smile:

https://github.com/driftyco/ionic-site/issues/604
