### ISSUE TITLE
Toast is in ionic-native module

### ISSUE THREAD

**Issue by zhaoshengjun** [driftyco/ionic-preview-app#36]
I was referencing the code from this [toast webapge](http://ionicframework.com/docs/v2/components/#toast), but the editor gave me an error which was saying Toast is not available. I tracked the source code into this repo and found out the same code:
```typescript
import {Toast} from "ionic-angular";
```

I had to dig it myself and found out the Toast component is not in `ionic-angular` but in `ionic-native`.

Please check it.

**Comment by brandyscarney** [comment]
There are two different Toast modules. 

The Toast component for the framework is found in `ionic-angular`, which is this: 
- http://ionicframework.com/docs/v2/components/#toggle
- http://ionicframework.com/docs/v2/api/components/toast/Toast/

The Toast in `ionic-native` is a wrapper for the cordova plugin: 
- http://ionicframework.com/docs/v2/native/toast/
- https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin

You can decide which one you want to use. Thanks! :)

**Comment by zhaoshengjun** [comment]
I think the reason is I am using ionic-angular v2.0.0-beta.3, which doesn't have a Toast in the component directory.

Thanks for the explanation!
