### ISSUE TITLE
ion-searchbar-  getItems($event) issue

### ISSUE THREAD

**Issue by Davidlala** [driftyco/ionic-preview-app#37]
this is my page5.html
```
<ion-navbar *navbar>
  <ion-title>

  </ion-title>
</ion-navbar>

<ion-content class="Page5">
  <ion-searchbar [(ngModel)]="searchQuery" (ionInput)="getItems($event)"></ion-searchbar>
  
 <ion-list>
   <ion-item *ngFor="let item of items">
     {{ item }}
   </ion-item>
 </ion-list>

</ion-content>

```

and this page5.ts

```
import ..
...
export class Page5{
getItems(searchbar) {
  
    console.log(searchbar);
}
```

when i start typing in the search bar, console showing nothing 

i need to see something like this:
if i type 'a' the console should show 'a' and then 
if i type 'b' the console should show 'ab'

**Comment by brandyscarney** [comment]
Can you paste the output of `ionic info` and is this in the preview app or your personal app?

**Comment by brandyscarney** [comment]
I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

Thanks so much!
