### ISSUE TITLE
Unable to launch the app

### ISSUE THREAD

**Issue by chandanch** [driftyco/ionic-preview-app#38]
Hello, When I updated from **ionic-angular2.0.0-beta.6** to **2.0.0-beta.7**. I get this error : **Cannot read property 'registerBackButtonAction' of undefined in app.js(line:31)** on browser. i.e on node_modules/ionic-angular/components/app/app.js

I followed the steps given here: https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#angular-update-to-200-rc1
Here is my package.json file:

```
{
"dependencies": {
"@angular/common": "^2.0.0-rc.2",
"@angular/compiler": "^2.0.0-rc.2",
"@angular/core": "^2.0.0-rc.2",
"@angular/http": "^2.0.0-rc.2",
"@angular/platform-browser": "^2.0.0-rc.2",
"@angular/platform-browser-dynamic": "^2.0.0-rc.2",
"@angular/router": "^3.0.0-alpha.6",
"es6-shim": "^0.35.0",
"ionic-angular": "^2.0.0-beta.7",
"ionic-native": "^1.1.0",
"ionicons": "3.0.0",
"reflect-metadata": "^0.1.2",
"rxjs": "^5.0.0-beta.6",
"zone.js": "^0.6.12"
},
"devDependencies": {
"del": "2.2.0",
"gulp": "3.9.1",
"gulp-watch": "4.3.5",
"ionic-gulp-browserify-typescript": "^1.1.0",
"ionic-gulp-fonts-copy": "^1.0.0",
"ionic-gulp-html-copy": "^1.0.0",
"ionic-gulp-sass-build": "^1.0.0",
"ionic-gulp-scripts-copy": "^2.0.0",
"run-sequence": "1.1.5"
},
"cordovaPlugins": [
"cordova-plugin-device",
"cordova-plugin-console",
"cordova-plugin-whitelist",
"cordova-plugin-splashscreen",
"cordova-plugin-statusbar",
"ionic-plugin-keyboard"
],
"cordovaPlatforms": [
"ios",
{
"platform": "ios",
"version": "",
"locator": "ios"
},
"android"
],
"name": "nanobi-analytics",
"description": "Nanobi Analytics: An Ionic project"
}
```
My Current ionic version is: 2.0.0-beta.30

**Comment by danzyltong** [comment]
Unable to launch block launcher. Pls help

**Comment by brandyscarney** [comment]
Can you run `ionic info` and paste the output? I think it may be upgrading to beta 8 which requires these steps to upgrade: https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#steps-to-upgrade-to-beta-8

Usually this error is caused by importing `IonicApp` which has been renamed to `App`.

**Comment by chandanch** [comment]
Hello I was able to resolve this issue, I did not bootstrap the app component. It is working fine now.
