### ISSUE TITLE
Dont work in IE

### ISSUE THREAD

**Issue by evgeniynet** [driftyco/ionic-preview-app#39]
doesn't even showed in IE 11

![image](https://cloud.githubusercontent.com/assets/1727207/16117831/b7c8b2de-33dc-11e6-90a3-9eaad04765a3.png)

![image](https://cloud.githubusercontent.com/assets/1727207/16117836/bdb8587a-33dc-11e6-8e5e-2bb63ff8c926.png)

**Comment by JarmoKukkola** [comment]
Even default template of Ionic 2 does not work with IE.

**Comment by mhartington** [comment]
Ionic does not support IE
