### ISSUE TITLE
Ionic serve blank page

### ISSUE THREAD

**Issue by juniorlinn** [driftyco/ionic-preview-app#4]
Hi, I have followed the steps provided in the README.md, but when I run Ionic serve, the only thing showing up in my browser is the iPhone style header.

![ionic-serve](https://cloud.githubusercontent.com/assets/11231830/13267768/0c6a0b42-da4d-11e5-9e1d-a7f2b64c93ec.png)

![screenshot 2016-02-23 16 46 30](https://cloud.githubusercontent.com/assets/11231830/13267790/1f108f64-da4d-11e5-9aa3-c589b3c6b55b.png)

**Comment by brandyscarney** [comment]
Can you check that `production` is set to `false` here? https://github.com/driftyco/ionic-preview-app/blob/master/app/app.ts#L13

**Comment by juniorlinn** [comment]
Thank you! 
Setting **production: false** solved the problem.

**Comment by brandyscarney** [comment]
Awesome. I updated the README to make this more clear. :) Thanks!
