### ISSUE TITLE
[solved] problem with .scss in action-sheets

### ISSUE THREAD

**Issue by RafaelLabinf** [driftyco/ionic-preview-app#40]
Hi,

My .scss file is not being recognized.
I'm trying to test this example in android and browser (following the Ionic 2 tutorial -> "http://ionicframework.com/docs/v2/components/#action-sheets" with this github code) and I'm not getting the icons colored (pink share icon, blue play icon, green favorite icon...).
I don't know if I have to do some special step... Can you help me?

These are my files:
.html:
```
<ion-navbar *navbar>
  <button menuToggle>
    <ion-icon name="menu"></ion-icon>
  </button>
  <ion-title>Notificaciones</ion-title>
</ion-navbar>


<ion-content padding class="action-sheets-basic-page">

  <h3>Action Sheets</h3>

  <button block (click)="openMenu()">
    Show Action Sheet
  </button>

</ion-content>
```

.js:
```
import {Component} from "@angular/core";
import {Platform, ActionSheet, NavController} from 'ionic-angular';


@Component({
  templateUrl: 'build/pages/notificaciones/notificaciones.html'
})
export class NotificacionesPage {
  static get parameters() {
    return [[Platform], [NavController]];
  }

  constructor(platform, nav) {
    this.platform = platform;
    this.nav = nav;
  }

  openMenu() {
    let actionSheet = ActionSheet.create({
      title: 'Albums',
      cssClass: 'action-sheets-basic-page',
      buttons: [
        {
          text: 'Delete',
          role: 'destructive',
          icon: !this.platform.is('ios') ? 'trash' : null,
          handler: () => {
            console.log('Delete clicked');
          }
        },
        {
          text: 'Share',
          icon: !this.platform.is('ios') ? 'share' : null,
          handler: () => {
            console.log('Share clicked');
          }
        },
        {
          text: 'Play',
          icon: !this.platform.is('ios') ? 'arrow-dropright-circle' : null,
          handler: () => {
            console.log('Play clicked');
          }
        },
        {
          text: 'Favorite',
          icon: !this.platform.is('ios') ? 'heart-outline' : null,
          handler: () => {
            console.log('Favorite clicked');
          }
        },
        {
          text: 'Cancel',
          role: 'cancel', // will always sort to be on the bottom
          icon: !this.platform.is('ios') ? 'close' : null,
          handler: () => {
            console.log('Cancel clicked');
          }
        }
      ]
    });

    this.nav.present(actionSheet);
  }
}
```

.scss:
```
.action-sheets-basic-page {
  .ion-md-share {
    color: #ED4242;
  }
  .ion-md-arrow-dropright-circle {
    color: #508AE4;
  }
  .ion-md-heart-outline {
    color: #D53131;
  }
  .action-sheet-cancel ion-icon,
  .action-sheet-destructive ion-icon {
    color: #757575;
  }
}
```

And this is the result:
http://imgur.com/I0ZyoAD

I'm getting this warning in chrome:
"Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator"

I don't know if it's related to my problem, but I guess may be...

Thanks in advance.

**Comment by brandyscarney** [comment]
Are you importing the Sass file in `theme/app.core.scss`? Something like this:

```
@import "../pages/action-sheets/basic/styles";
```

**Comment by RafaelLabinf** [comment]
Of course, it was the problem with my code.
Now I have my icons colored :)

Thank you very much!!

P.S.: I continue getting 2 warnings in chrome:
1: Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
2: Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.

**Comment by brandyscarney** [comment]
These warnings won't break your app. The first warning is just letting you know that StatusBar doesn't exist on the browser, only on a cordova device. The second is a chrome warning: crbug.com/574343, but we don't have a valid solution for hiding it: https://forum.ionicframework.com/t/warning-deferred-long-running-timer-task-s/51170

Going to close this though since the issue was resolved. Thanks!

**Comment by thorizer** [comment]
I have the same issue. How to import the Sass file in ionic 3?

**Comment by tamiryan** [comment]
Hey. I also have the same problem with Action Sheets. Can you please let me know where and exactly how should I import my css file ? Under theme folder there is only one file called variables.scss . Thank you beforehand.

**Comment by brandyscarney** [comment]
@tamiryan The replies in this issue aren't relevant anymore since the directory structure has changed. I recommend taking a look at how the conference app works with stylesheets for each page: https://github.com/ionic-team/ionic-conference-app

For example, the tutorial styles are here: https://github.com/ionic-team/ionic-conference-app/blob/master/src/pages/tutorial/tutorial.scss

All *.scss files should automatically be imported now. If you still have questions please ask on our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/). :smile:
