### ISSUE TITLE
Search not working in toolbar with Searchbar

### ISSUE THREAD

**Issue by chandanch** [driftyco/ionic-preview-app#41]
Hello, Search is not working in toolbar with searchbar in the preview app. Its not working in the main document website as well
http://ionicframework.com/docs/v2/components/#toolbar-searchbar

It throwing this error : 
**Cannot read property 'trim' of undefined at SearchbarPage.getItems (pages.ts:37)**

Full stack trace:

> zone.js:260 Uncaught EXCEPTION: Error in build/pages/toolbar/searchbar/template.html:1:43
> ORIGINAL EXCEPTION: TypeError: Cannot read property 'trim' of undefined
> ORIGINAL STACKTRACE:
> TypeError: Cannot read property 'trim' of undefined
>     at SearchbarPage.getItems (http://ionicframework.com/dist/preview-app/www/build/js/app.bundle.js:3056:14)
>     at DebugAppView._View_SearchbarPage1._handle_input_2_1 (SearchbarPage.template.js:336:35)
>     at http://ionicframework.com/dist/preview-app/www/build/js/app.bundle.js:28984:24
>     at http://ionicframework.com/dist/preview-app/www/build/js/app.bundle.js:37931:36
>     at http://ionicframework.com/dist/preview-app/www/build/js/app.bundle.js:38001:93
>     at ZoneDelegate.invoke (http://ionicframework.com/dist/preview-app/www/build/js/zone.js:323:29)
>     at Object.onInvoke (http://ionicframework.com/dist/preview-app/www/build/js/app.bundle.js:33562:41)
>     at ZoneDelegate.invoke (http://ionicframework.com/dist/preview-app/www/build/js/zone.js:322:35)
>     at Zone.runGuarded (http://ionicframework.com/dist/preview-app/www/build/js/zone.js:230:48)
>     at NgZoneImpl.runInnerGuarded (http://ionicframework.com/dist/preview-app/www/build/js/app.bundle.js:33595:78)
> ERROR CONTEXT:
> [object Object]
> 

It was working earlier on the docs site now its not working

**Comment by brandyscarney** [comment]
Thanks for the issue! I fixed this in the preview app and it will be live on the site as soon as we finish some updates. :smile:
