### ISSUE TITLE
Slides bug

### ISSUE THREAD

**Issue by haokur** [driftyco/ionic-preview-app#46]
the Component Slides can not run pretty with android

**Comment by 1415003719** [comment]
@haokur I have the same issue

**Comment by brandyscarney** [comment]
I believe this is the same issue as https://github.com/driftyco/ionic/issues/7408. I am going to close this as a duplicate of that but if this issue is different please create a new issue using the issue form on the ionic repository: https://github.com/driftyco/ionic/issues/new

Thanks!
