### ISSUE TITLE
Slides not working on Android

### ISSUE THREAD

**Issue by AriGru** [driftyco/ionic-preview-app#47]
Hello - I have built slides and they work on GenyMotion but we submitted the app and they do not work on Android. It shows I have one slide and will not scroll through. Is this being fixed?

**Comment by danielmouraa** [comment]
+ 1

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic#7408

**Comment by brandyscarney** [comment]
Thanks for the issue! I've moved this issue over to the `ionic` repository. Please report any issues with the framework there as we review them more often there. :)
