### ISSUE TITLE
energized color on <ion-toggle> not work

### ISSUE THREAD

**Issue by pelao** [driftyco/ionic-preview-app#48]
Hi!, I tryed to set color energized  on tag `"<ion-toggle energized checked="false"></ion-toggle>"` but not set this color, in browser ionic show the color by default "blue" on toggle button.

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:
