### ISSUE TITLE
Position does not exist in type Toast Option

### ISSUE THREAD

**Issue by Ghayyas** [driftyco/ionic-preview-app#49]
I tried the following code but its not working it gives me error..

    showToast(position: string) {
      
     let toast = Toast.create({
      message: 'Mmmm, buttered toast',
      duration: 2000,
      position: position
    });
    
    this.nav.present(toast);
    }

It give me error.. How can I set position of Toast?

**Comment by brandyscarney** [comment]
Can you run `ionic info` in your command prompt/terminal from within your project folder and paste the output here? This was introduced in `beta 9` so you may be using an older version of the framework.

**Comment by Ghayyas** [comment]
Here is My Ionic Info

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
Node Version: v4.4.7

**Comment by brandyscarney** [comment]
So you are still using `beta 8` of the framework:

> Ionic Framework Version: 2.0.0-beta.8

You'll need to update to `beta 9` (or higher) in order to use the position in toast. Please see the changelog for breaking changes and steps to upgrade: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-beta-10
