### ISSUE TITLE
How to Hide Ion-tabs on specific page in ionic2

### ISSUE THREAD

**Issue by Ghayyas** [driftyco/ionic-preview-app#50]
Hi @brandyscarney  Please Guid me.. I want to hide tabs in one page.. and want to show three others tab on only that page. How can i do that?

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:
