### ISSUE TITLE
itemTapped 

### ISSUE THREAD

**Issue by Bforsyth1234** [driftyco/ionic-preview-app#51]
The itemTapped function has a bug. It refers this.Nav not this.navCtrl

From:

`  itemTapped(event, item) {
    this.nav.push(ItemDetailsPage, {
      item: item
    });
  }`

To:

`  itemTapped(event, item) {
    this.navCtrl.push(ItemDetailsPage, {
      item: item
    });
  }`

**Comment by brandyscarney** [comment]
Thanks for the issue. I've fixed this in the tutorial and sidemenu starter. I'm not seeing any issues with this in this repo. :) 

https://github.com/driftyco/ionic2-starter-sidemenu/commit/6d82ce8887cde14d029c4ec4a411b1fde18e4aa8
https://github.com/driftyco/ionic2-starter-tutorial/commit/abab379a5af64bb7463106e9105884b0b09899aa

**Comment by brandyscarney** [comment]
Where are you seeing this function? It isn't used in this repo.

**Comment by Bforsyth1234** [comment]
@brandyscarney  Sorry wrong place too many tabs open. I was referring to the ionic2 starter tutorial =)
https://github.com/driftyco/ionic2-starter-tutorial/blob/master/app/pages/list/list.ts

**Comment by brandyscarney** [comment]
Oh ok :) It looks like it was updated 2 days ago, are you still seeing it when starting a new project?
