### ISSUE TITLE
Buttons with *ngIf inside toolbars/navbars: the classname “button” incorrectly added

### ISSUE THREAD

**Issue by infinnie** [driftyco/ionic-preview-app#52]
I am using Ionic 2 Beta 10.

When I wrote in the HTML file:
```html
<ion-header>
    <ion-toolbar primary>
        <ion-buttons end>
            <button *ngIf="!hasSearch">Filter</button>
            <button>Do something</button>
        </ion-buttons>
        <ion-title>TestCase</ion-title>
    </ion-toolbar>
</ion-header>
```
And the variable hasSearch evaluated to false, the class “button” would be incorrectly added to the former button, but not the latter one.

**Comment by brandyscarney** [comment]
Thanks for the issue! This repository is for issues related to the component demos. If you believe you have found a bug with the framework, please create an issue on the `ionic` repository, by filling out the issue template: https://github.com/driftyco/ionic/issues/new

I am not able to reproduce this issue with `beta 11`, so I believe it has been fixed. Please upgrade to beta 11 to see if you still have this issue prior to creating a new issue: https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-beta11-2016-08-05

Thanks!
