### ISSUE TITLE
Ionic 2 beta 11 issue having in loading screen.

### ISSUE THREAD

**Issue by Ghayyas** [driftyco/ionic-preview-app#55]
Hi, few hours ago I update my project to ionic 2 beta 11. There is lots of changes their. Im using loading on some of my few screen.. Loading works.. I never stops and start blinking. I flow your all steps but still having this issue..

My Code:  
` let load = this.loading.create({
                   content: "Please wait...",
               //  duration: 300, 
                   dismissOnPageChange: true
             });
                   load.present();`

Beacuse Im getting response from server... I typed it after data response

`load.dismiss(true)`

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If you think this is a bug with the framework itself, please create a new issue on the `ionic` repository by filling out the issue template: https://github.com/driftyco/ionic/issues/new

Please include a plunker or repository with steps to reproduce. Thanks!

Also make sure to take a look at the API documentation as that may solve your problem: http://ionicframework.com/docs/v2/api/components/loading/LoadingController/#usage
