### ISSUE TITLE
Arrows error on first and last component.

### ISSUE THREAD

**Issue by dmvvilela** [driftyco/ionic-preview-app#57]
**Note: If you are having problems formatting your issue please refer to this article on using markdown in Github:**

https://guides.github.com/features/mastering-markdown/

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Hi. When i am on the first component, and use the back arrow on the screen like two times.. I have to click the front arrow three times to go to next component. The same happens when i am on the last component ant click on the forward arrow some times.. The same number of times have to be clicked on back arrow to go to the previous component.

#### What behavior are you expecting?
If i am on the first component.. Clicking on back arrow should do nothing.. And even if i click 10 times on that, clicking one time on forwarding arrow should go to the next component page. The same with the last one.

**Steps to reproduce:**
1. Go to the first page.
2. Click back arrow a few times.
3. Click on the forward arrow.

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by danbucholtz** [comment]
This is fixed in my changes the past few days.

Thanks for contributing!

Thanks,
Dan
