### ISSUE TITLE
add ability to load page in development mode using a location #hash

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic-preview-app#6]
Navigating using the arrow buttons takes too long if the view being worked on is not in the first few. Add ability to navigate to `/#modals` to load the modal page

**Comment by brandyscarney** [comment]
You might be able to use this: https://github.com/driftyco/ionic/tree/2.0/ionic/components/nav/test/routing

**Comment by drewrygh** [comment]
Perfect :+1:

**Comment by brandyscarney** [comment]
I created a new branch for this where it is working, but there are some more changes I want to make so I just pushed this: https://github.com/driftyco/ionic-preview-app/tree/route-config-refactor

**Comment by brandyscarney** [comment]
I removed the fab buttons for navigation and instead pushed all of the routes to the side menu, so you can now navigate to any page from the sidemenu when production is false.

![screen shot 2016-03-08 at 8 21 58 pm](https://cloud.githubusercontent.com/assets/6577830/13622266/82039886-e56b-11e5-8728-79b934022463.png)

**Comment by brandyscarney** [comment]
Ok passing the `production` flag as a query string now, this way users can run the app without having to worry about production mode. :smile:
