### ISSUE TITLE
V2 Docs "demo source" links are wrong

### ISSUE THREAD

**Issue by yannbf** [driftyco/ionic-preview-app#60]
The folder structure in this repository was changed, so all of the "demo source" links from documentation should now point from "..ionic-preview-app/tree/master/**app**/.." to "..ionic-preview-app/tree/master/**src**/.." 

Example: http://ionicframework.com/docs/v2/components/#datetime

**Comment by sridharan31** [comment]
demo source links are not wrong https://github.com/driftyco/ionic-preview-app/tree/master/app/pages/navigation/basic

**Comment by solsticesurfer** [comment]
I agree, the documentation needs to be updated to reflect the new repository structure. Basically, in the URLs to the demo code, "app" needs ti be changed to "src".

Example:
Current URL in documentation: https://github.com/driftyco/ionic-preview-app/tree/master/**app**/pages/modals/basic

Actual URL in documentation: https://github.com/driftyco/ionic-preview-app/tree/master/**src**/pages/modals/basic

**Comment by solsticesurfer** [comment]
This bug should be reported at https://github.com/driftyco/ionic-site/issues

**Comment by fiznool** [comment]
This has now been fixed: https://github.com/driftyco/ionic-site/issues/799
