### ISSUE TITLE
Trouble when run command `ionic run android`

### ISSUE THREAD

**Issue by quangpdt** [driftyco/ionic-preview-app#67]
After resolve issue #66 , I keep facing with another problem, when I tried to run `ionic run android`, I met this error:

> [11:40:50]  Error: Error at C:/Users/quang/Desktop/ionic-preview-app-master/.tmp/directives/helpers.ts:64:17
> [11:40:50]  Return type of exported function has or is using name 'AdvancedMapPage' from external module
>             "C:/Users/quang/Desktop/ionic-preview-app-master/.tmp/pages/cards/advanced-map/pages" but
>             cannot be named.
> [11:40:50]  Error at C:/Users/quang/Desktop/ionic-preview-app-master/.tmp/directives/helpers.ts:64:17
> [11:40:50]  Return type of exported function has or is using name 'AdvancedSocialPage' from external
>             module "C:/Users/quang/Desktop/ionic-preview-app-master/.tmp/pages/cards/advanced-social/pages"
>             but cannot be named.
> [11:40:50]  Error at C:/Users/quang/Desktop/ionic-preview-app-master/.tmp/directives/helpers.ts:64:17
> [11:40:50]  Return type of exported function has or is using name 'AvatarPage' from external module "C:/Users/quang/Desktop/ionic-preview-app-master/.tmp/pages/lists/avatar/pages"
>             but cannot be named.
> [11:40:50]  Error at C:/Users/quang/Desktop/ionic-preview-app-master/.tmp/directives/helpers.ts:64:17
> [11:40:50]  Return type of exported function has or is using name 'BackgroundPage' from external module
>             "C:/Users/quang/Desktop/ionic-preview-app-master/.tmp/pages/cards/background/pages" but cannot
>             be named.

Do you have any idea to resolve it? I completely stuck :(

**Comment by brandyscarney** [comment]
There are some issues with the AoT compiler that need to be fixed. You can use the dev build (but it won't be as fast to startup): https://github.com/driftyco/ionic-preview-app/commit/d623969343184d282c12001d5b21c774675fe711

**Comment by brandyscarney** [comment]
This should be fixed now with the latest code, thanks!
