### ISSUE TITLE
Ionic tabs seems not to be aligned horizontally very well

### ISSUE THREAD

**Issue by kluz116** [driftyco/ionic-preview-app#68]
Ionic tabs seems not to be aligned horizontally very well.... All components seems not to very aligned horizontally when i run this on my android phone.. But in the development browser, very thing is aligned very well.
![ionic2](https://cloud.githubusercontent.com/assets/9973896/19774256/2abd80c0-9c75-11e6-93cd-98fb1da5944f.jpg)
![ionic1](https://cloud.githubusercontent.com/assets/9973896/19774298/3d25eca2-9c75-11e6-81ee-58ee6eaea3a7.jpg)

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic#8932
