### ISSUE TITLE
showPrompt

### ISSUE THREAD

**Issue by laubia1314** [driftyco/ionic-preview-app#69]
You have an error in the name of the function called. You should change showPrompt for doPrompt

**Comment by brandyscarney** [comment]
Where is there an error? I'm not seeing `showPrompt` anywhere: https://github.com/driftyco/ionic-preview-app/search?utf8=%E2%9C%93&q=showPrompt

**Comment by tareksmoubarak** [comment]
I'm not seeing `showPrompt` anywhere too !

**Comment by brandyscarney** [comment]
I'm going to close this since I can't find it, but if you find the file it is in please link it here. Thanks!
