### ISSUE TITLE
Alert definition - to replace body with message?

### ISSUE THREAD

**Issue by Tommertom** [driftyco/ionic-preview-app#7]
Hi

Shouldnt the alert definition have message: 'message'  instead of body:'message'? At least it seems after upgrading to beta, the definition has changed...

    let alert = Alert.create({
      title: 'New Friend!',
      body: 'Your friend, Obi wan Kenobi, just accepted your friend request!',
      buttons: ['Ok']
    });

to change in...

    let alert = Alert.create({
      title: 'New Friend!',
      message: 'Your friend, Obi wan Kenobi, just accepted your friend request!',
      buttons: ['Ok']
    });

regards

Tom

**Comment by brandyscarney** [comment]
Yes, you are correct. It has been fixed now, thanks!
