### ISSUE TITLE
Pan Gesture not working

### ISSUE THREAD

**Issue by cryo243** [driftyco/ionic-preview-app#70]
Hi,
I tried replicating the gesture examples.  I just cloned the ionic preview app on my machine. Only the tap event is getting fired the rest : Swipe, Pan and Press gestures are not working. Please assist

**Comment by cryo243** [comment]
> Just an update on the issue above I noticed that the panleft and panright event only occurs after refresh. It does not work when the app launches for the first time.

**Comment by brandyscarney** [comment]
Thanks for the issue! Are you still seeing this problem using the latest code and running a production build?

**Comment by brandyscarney** [comment]
Closing this as it's been awhile since there was a reply, thanks!

**Comment by cryo243** [comment]
Hi,
Sorry yes you can close the issue, sorry for the late reply. Thanks
