### ISSUE TITLE
Uncaught (in promise): false

### ISSUE THREAD

**Issue by hhafeng** [driftyco/ionic-preview-app#78]
Why dismissOnPageChange will be wrong for true?   **Uncaught (in promise): false**
```
presentLoading() {
    let loading = this.loadingCtrl.create({
      content: "Please wait...",
      duration: 3000,
      dismissOnPageChange: true
    });
    loading.present();
}
```

**Comment by brandyscarney** [comment]
Please see this issue on Ionic: https://github.com/driftyco/ionic/issues/9589

It will be fixed in the next release and is also fixed in the nightly here:
https://github.com/driftyco/ionic/issues/9589#issuecomment-268561129
