### ISSUE TITLE
icons not getting displayed on ios 5

### ISSUE THREAD

**Issue by gppraveena** [driftyco/ionic-preview-app#81]

**Comment by brandyscarney** [comment]
@gppraveena Can you provide some more information please? Do you mean an iPhone 5? Are you running the app from the `ionic` command in the command line or through xCode? Is this just on the preview app or your own project as well? Are you talking about the homescreen icon or ionicons?

**Comment by gppraveena** [comment]
I am using visual studio 2015 and chrome browser for the ios Ripple. I had to make some slight changes like below for the icons to appear.

<ion-header>
    <ion-navbar>
        <ion-title>MyApp</ion-title>
        <ion-buttons start>
            <button ion-button clear small color="light" icon-left>
                <ion-icon name='settings'></ion-icon>
            </button>
        </ion-buttons>
        <ion-buttons end>
            <button ion-button clear small color="light">
                <ion-icon name='apps'></ion-icon>
            </button>
        </ion-buttons>
    </ion-navbar>
</ion-header>
