### ISSUE TITLE
Deprecated: the color input has been removed from HTML

### ISSUE THREAD

**Issue by peterennis** [driftyco/ionic-preview-app#82]
Windows 10
ionic serve --lab --browser chrome

![capture019](https://cloud.githubusercontent.com/assets/140737/21753961/fc393f76-d5ab-11e6-81f8-c2adfacc8aed.PNG)

**Comment by brandyscarney** [comment]
Thanks, we've fixed this on the branch so it will be removed when the branch is merged: https://github.com/driftyco/ionic-preview-app/tree/rc.5
