### ISSUE TITLE
display issues with lab

### ISSUE THREAD

**Issue by peterennis** [driftyco/ionic-preview-app#83]
Windows 10

![capture020](https://cloud.githubusercontent.com/assets/140737/21753994/7351387a-d5ac-11e6-88a9-43c358cfef88.PNG)

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-cli#1870

**Comment by brandyscarney** [comment]
Closing in favor of https://github.com/driftyco/ionic-cli/issues/1870. This will need to be handled via the CLI.
