### ISSUE TITLE
ion-item-sliding is wrong with two ion-select

### ISSUE THREAD

**Issue by zengchuan** [driftyco/ionic-preview-app#85]
in ion-item-options I have two ion-select and it is wrong

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the preview app, please provide more information in order for us to reproduce the issue.

Thanks so much!
