### ISSUE TITLE
Ionic 2 - Ion Fab Button - If  click outside not close automatic

### ISSUE THREAD

**Issue by rendy14s** [driftyco/ionic-preview-app#88]
Hello.. 
i have ion fab button in my home. 
i have problem and till now cant solved.

- i have read on this post https://forum.ionicframework.com/t/ionic-2-fab-list-click-outside-to-close/67135

- #fab fab.close()

but not work on me,

so, 
1. If i click fab button is show the menu. and if i click else (outside fab : touch else) the fab not close automatic.

2. Menu is show on fab button. if i click that other menu. and open a page. and i back again. fab button still open.

anyone can solved my problem ? thanks

**Comment by vishaltechreceptives** [comment]
any solutions for above issues??

**Comment by rendy14s** [comment]
this solved.

#10198
