### ISSUE TITLE
Error: File to import not found or unreadable: ionic.ios

### ISSUE THREAD

**Issue by MrBokeh** [driftyco/ionic-preview-app#9]
When I run ionic serve, here is the error:
 
✗ app/theme/app.ios.scss
Error: File to import not found or unreadable: ionic.ios
       Parent style sheet: stdin
        on line 20 of stdin
>> @import "ionic.ios";
   ^

**Comment by brandyscarney** [comment]
What steps did you take prior to running ionic serve? https://github.com/driftyco/ionic-preview-app#installation--development

**Comment by brandyscarney** [comment]
Ignore my last comment - I was able to reproduce this. Should be fixed now with the latest code. Thanks for the issue!

**Comment by eillarra** [comment]
Line 18 should be fixed too... https://github.com/driftyco/ionic-preview-app/blob/master/ionic.config.js#L18

**Comment by brandyscarney** [comment]
Thanks. Fixed!
