### ISSUE TITLE
After IONIC SERVE there is only a blank screen

### ISSUE THREAD

**Issue by renatopcamara** [driftyco/ionic-preview-app#92]
After following instructions at readme.MD and the command IONIC SERVE I got only a blank screen.
Here is the config info:
$ npm -v
4.1.1
$ ionic info
Your system information:
Cordova CLI: 6.4.0
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v5.12.0

What am I doing wrong?

**Comment by Suraj-Tiwari** [comment]
Have you checked Console for any error?

**Comment by Bordotti** [comment]
Hello Renato, you are right, but now you have new steps, you can look into ionic-preview-app/src/pages/tabs/ and create inside of one folder of this a file NAME_PAGE.html then you will can see something running, because this server will run your app, and if you don't give him any task, the server will just wait and you will see this black screen.
Hope I could help you, I didn't build the app using git, I've built it directly on my PC and use this documentation only to help in some parts.

**Comment by renatopcamara** [comment]
Hi Bordotti, Sorry it didn't work or I don't understand your instructions. If you can be more precise I would appreciate.
I'm running on my PC with Windows.

These are the Console Errors when I refresh the page:
GET http://localhost:8100/build/main.css localhost/:54 
GET http://localhost:8100/build/polyfills.js localhost/:66 
GET http://localhost:8100/build/main.js localhost/:69 
GET http://localhost:8100/build/main.css (index):54 
GET http://localhost:8100/build/polyfills.js (index):66
GET http://localhost:8100/build/main.js (index):69

**Comment by Suraj-Tiwari** [comment]
I will suggest you to setup a fresh project using Ionic

**Comment by Suraj-Tiwari** [comment]
i have downloaded this project and extracted all files and moved all files from `ionic-preview-app-master` to a separate folder and then used command `npm install` then `ionic serve` and it's working fine. have a look at this screenshot.
![screenshot_1](https://cloud.githubusercontent.com/assets/22210490/23643089/7c251c0e-0325-11e7-9c73-6f49e54ff550.png)

**Comment by renatopcamara** [comment]
Hi Suraj-Tiwari,
I will try to start a brand new project and copy the folders inside. Can you please send me a Screenshots of your the files structure? 
Thanks.

**Comment by Suraj-Tiwari** [comment]
Don't start the new project just copy the project to another folder 
this is my File structure
![screenshot_1](https://cloud.githubusercontent.com/assets/22210490/23655331/a12e7f06-035a-11e7-88c4-41c6338f0a37.png)

**Comment by renatopcamara** [comment]
Hi Suraj-Tiwari,

I copy the entire folder and then run npm install and then ionic serve. The blank screen showed up again.
When I run npm install there were some warnings:
> $ npm install
npm WARN prefer global node-gyp@3.5.0 should be installed with -g
> node-sass@4.5.0 install C:\nodejs\apps\ionic-app\node_modules\node-sass
> node scripts/install.js
Cached binary found at C:\Users\Renato\AppData\Roaming\npm-cache\node-sass\4.5.0                          \win32-x64-47_binding.node
> node-sass@4.5.0 postinstall C:\nodejs\apps\ionic-app\node_modules\node-sass
> node scripts/build.js
Binary found at C:\nodejs\apps\ionic-app\node_modules\node-sass\vendor\win32-x64                          -47\binding.node
Testing binary
Binary is fine
ionic-hello-world@ C:\nodejs\apps\ionic-app
+-- @angular/common@2.2.1
+-- @angular/compiler@2.2.1
.
.
.

At the end there were also some others warnings:
+-- UNMET PEER DEPENDENCY sw-toolbox@*
+-- typescript@2.0.9
`-- zone.js@0.6.26
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch                          okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                          1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                          )
npm WARN @ionic/app-scripts@1.1.3 requires a peer of sw-toolbox@* but none was i                          nstalled.


Are these warnings the reason of the error? 
My file structure is exact the same as yours. I just did a copy of the folder as you suggested.

**Comment by renatopcamara** [comment]
I have just realized that I dont have the folder BUILD inside the WWW folder. I only have ASSETS.
How to create the BUILD folder?

**Comment by Suraj-Tiwari** [comment]
Sorry For the Delay I was recently Busy.
Please Update your Node Packages, issue will be resolved.
