### ISSUE TITLE
ion-checkbox in iphone can't click

### ISSUE THREAD

**Issue by HaHaHaHaHaHaHaaaaaa** [driftyco/ionic-preview-app#94]
i can click the checkbox in chrome simulator,but in iphone  not,  android is normal.

**Comment by brandyscarney** [comment]
Thanks for the issue! Could you provide some more information please? What command are you running? Which device are you using to test? How can we reproduce this? Thanks!

**Comment by brandyscarney** [comment]
I haven't been able to reproduce this issue using an iPhone 6. If you are still running into this issue please provide us some steps to reproduce it and I will reopen. Thanks!
