### ISSUE TITLE
found a bug when ion-slider under ion-silder

### ISSUE THREAD

**Issue by alucard263096** [driftyco/ionic-preview-app#95]
Hi All,

Below is the layout of my design and it is very normal. Anyway, i found a issue here.

**What is the layout now**
&lt;ion-segment (ionChange)="changeTheTabsSilder" &gt;
	&lt;ion-segment-buttion&gt;
		Tab1
	&lt;/ion-segment-buttion&gt;
	&lt;ion-segment-buttion&gt;
		Tab2
	&lt;/ion-segment-buttion&gt;
	&lt;ion-segment-buttion&gt;
		Tab1
	&lt;/ion-segment-buttion&gt;
&lt;/ion-segment&gt;

&lt;ion-silders **#TabsSilder**&gt;
      &lt;ion-silder&gt;
		&lt;ion-silders **#BannerSilder**&gt;
			&lt;ion-silder&gt;
			&lt;/ion-silder&gt;
			...//5 silders of banner
		&lt;ion-silders&gt;
	  &lt;/ion-silder&gt;
      &lt;ion-silder&gt;
		&lt;div&gt;Content&lt;/div&gt;
	  &lt;/ion-silder&gt;
      &lt;ion-silder&gt;
		&lt;div&gt;Content&lt;/div&gt;
	  &lt;/ion-silder&gt;
&lt;/ion-silders&gt;

in this layout, the segment control the TabsSilder and silde the TabsSilder to change the segment. 
And we have a silders BannerSilder in the first silder of TabsSilder

**Issue**
* As you see the page_mark of BannerSilder below. You will see there are 8 page here. Indeed we have 5 silder. So, i guess it should total 8 silder in all in this page.
* When you silder to the 5th silder and you still can silder right to 6th, 7th, 8th.

**Question**
Is really this a bug? Or how you guys design like my layout? I thought my design is very normal. Thanks.

![untitled](https://cloud.githubusercontent.com/assets/621332/24087486/ad314a08-0ced-11e7-92be-a0d73b9917dd.png)

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the preview app, please provide more information in order for us to reproduce the issue.

Thanks so much!
