### ISSUE TITLE
Error in ./NavigationDetailsPage class NavigationDetailsPage - caused by: Cannot read property 'color' of undefined

### ISSUE THREAD

**Issue by sip5** [driftyco/ionic-preview-app#99]
Hi, I am trying to set tp a basic navigation page list. 
i copied the Basic navigation to my app in order to begin the paging aspect but it is giving me no error in the terminal but when navigation.html is open, 
_"Error in ./NavigationDetailsPage class NavigationDetailsPage - caused by: Cannot read property 'color' of undefined"_
this error shows up
Need help. Thanks

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the preview app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the preview app, please provide more information in order for us to reproduce the issue.

Thanks so much!
